name: Build HKL Agent Installer

on:
  push:
    branches:
      - main


jobs:

  build:

    runs-on: windows-latest


    steps:

    - name: Pobierz kod
      uses: actions/checkout@v4


    - name: Instalacja Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"


    - name: Budowanie agenta Windows
      shell: cmd
      run: |

        cd agent

        set GOOS=windows
        set GOARCH=amd64

        go build -ldflags="-H windowsgui" -o HKL-Agent.exe


    - name: Budowanie instalatora
      shell: cmd
      run: |

        cd installer

        go build -o HKL-Agent-Installer.exe


    - name: Zapis plików
      uses: actions/upload-artifact@v4
      with:

        name: HKL-Agent-Windows

        path: |

          agent/HKL-Agent.exe

          installer/HKL-Agent-Installer.exe
