name: Build HKL Installer

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Pobierz kod
      uses: actions/checkout@v4


    - name: Instalacja Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"


    - name: Budowanie agenta
      shell: cmd
      run: |
        set GOOS=windows
        set GOARCH=amd64
        go build -ldflags="-H windowsgui" -o HKL-Agent.exe


    - name: Sprawdzenie pliku
      run: dir


    - name: Zapisz EXE
      uses: actions/upload-artifact@v4
      with:
        name: HKL-Agent
        path: HKL-Agent.exe
